### ISSUE TITLE
CMake class removes "install" directory

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/basement#138]
[Here](https://github.com/BobBuildTool/basement/blob/b0776cdb84327ecc3d5dff8f33ca64aab5a7171b/classes/cmake.yaml#L138) the CMake class removes the `install` directory before creating a new one and building. The Autotools class does nothing alike. Is either one of these an oversight or is there a reasoning behind that?

The reason I'm asking is that I myself have a class that creates files in the `install` directory which are then removed by the CMake class. I'd rather avoid putting this into a function that I have to remember to call in each recipe after building, if possible.

**Comment by jkloetzke** [comment]
It's an optimistic optimization in the autotools class. But actually it's a bug. The rationale is the following: "make install" will just copy the files to the "install" directory. If you work on a package and build it *incrementally* the files will keep piling up and removed files will still be around. I had this issue some time in the past and since then the "install" directory is always removed.

Now practically nobody does develop on autotools based packages because this requires a run of `autoreconf` or friends. Hence the safety net is not really required. But strictly speaking the `rm -rf install` should also be in the autotools class.
