### ISSUE TITLE
add cross-compilation support for git

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#142]
https://github.com/BobBuildTool/basement/blob/cbd2542abc66ba3df1636fb560681be1ab1623d2/recipes/devel/git.yaml#L24-L38

currently it is not possible to cross-compile git, because of missing `--build` argument, we should add this.

**Comment by Ferruck** [comment]
As discussed with @jkloetzke in https://github.com/BobBuildTool/basement/pull/136#discussion_r874976361 it's not as easy as adding the `--build` parameter. Git has some `configure` checks which run actual test programs (which of course fails when cross-compiling). You'd have to set the respective `ac_` variables in advance in order to keep the `configure` script from trying to do this. The actual hard part is to get the correct settings for those variables, though, as they depend on - for example - the target libc.
