### ISSUE TITLE
idea behind host-toolchain and target-toolchain

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#16]
hi.

currently we use root recipe depends order like this:

- host-toolchain 
- host-tools
- target-toolchain
- tgt packages

well that works fine so far. BUT more intuitive it would be if we could use this:

- host-toolchain 
- target-toolchain
- tgt packages

and now a tgt/dev packages could use `buildTools: host-toolchain` if that package have to be build with host-toolchain.

but that, the host-toolchain have to provide the environment variables, not done here:
https://github.com/BobBuildTool/basement/blob/cfc1360a853461b868b8157704225527fe2e6b30/classes/sandbox-toolchain.yaml#L49
https://github.com/BobBuildTool/basement/blob/cfc1360a853461b868b8157704225527fe2e6b30/recipes/devel/host-compat-toolchain.yaml#L85

also all build-tools have to  be supportet, like cmake, which will need stuff like `CMAKE_GENERATOR, CMAKE_GENERATOR_PLATFORM, CMAKE_GENERATOR_TOOLSET, CMAKE_BUILD_TYPE, CMAKE_TOOLCHAIN_FILE`...?

> The environment attribute provides the ability to define environment variables that are automatically picked up by the recipe where the tool is used. 
> https://bob-build-tool.readthedocs.io/en/latest/manual/configuration.html#providetools

**Comment by mahaase** [comment]
update: the only variable we need for cross-compiling is: `CMAKE_TOOLCHAIN_FILE`? 
the other variables doesn't depend on build-target.

and so the current solution should already work like described because of the toolchain file: 
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/classes/cmake.yaml#L32

so it shouldn't be necessary to add cmake here:
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/classes/basement/rootrecipe.yaml

we also could add it here:
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/classes/cmake.yaml

couldn't we?

but we should add buildTools: host-toolchain here: 
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/recipes/devel/cmake.yaml#L37
and why bootstrap uses target-toolchain?
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/recipes/devel/cmake.yaml#L53

**Comment by jkloetzke** [comment]
The idea behind host-toolchain and target-toolchain are a bit more subtle. They could refer to different toolchains or even to the same! The target toolchain is basically used by all packages that need to compile c or c++ code. The package itself should never know if this is really a cross compiling toolchain or if the target-toolchain builds for the host. This should be determined upstream in the recipes where the build environment is controlled.

The host-toolchain is *additionally* needed by some recipes because their packages need the target compiler and the host compiler simultaneously. The host-toolchain is used by them to build some intermediate tools during the build process that are *not* included in the result of the package. See the Linux kernel recipe as an example.

Bob gained a feature recently to remap toolchains for dependencies. See https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/recipes/kernel/linux.yaml#L73 for an example. There the target-toolchain for these dependencies is set to the host-toolchain. Therefore they will be compiled for the host while the kernel might be cross compiled.

Your schema also won't work because if a recipe needs both toolchains then they must not define the same variables. Otherwise Bob would not know what variable to take. In fact you will get an error in this case.

But even if that would work it is still not a good approach. The power of Bob and the recipes lies in the fact that a recipe does not need to care about the target platform. This should be controlled upstream in the recipes so that the same recipe can be used in multiple branches of the dependency tree and be compiled for the host and the target in the same project. Otherwise we would be an explicit host and target multiPackage for each recipe that may be compiled for the host too.

**Comment by mahaase** [comment]
thank u, for the detailed input!

> But even if that would work it is still not a good approach. The power of Bob and the recipes lies in the fact that a recipe does not need to care about the target platform. This should be controlled upstream in the recipes so that the same recipe can be used in multiple branches of the dependency tree and be compiled for the host and the target in the same project. Otherwise we would be an explicit host and target multiPackage for each recipe that may be compiled for the host too.

u've convinced me. that was the answer i'm searching for 👍
