### ISSUE TITLE
difference between cmake-bootstrap and cmake?

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#18]
hi.

what is the difference between cmake-bootstrap and cmake.
cmake-bootstrap should build the cmake.

is the idea, that cmake could be updated, but it isn't necessary to rebuild the bootstrap?
but than, we have to split it into 2 recipes, with 2 versions?

**Comment by jkloetzke** [comment]
Cmake has a circular dependency on itself. To compile cmake you need cmake. The bootstrap package builds a self contained, statically linked version where all dependencies are included in the cmake source tree. This version is then used to build cmake with its dependencies in the usual way so that all libraries are defined by the recipes rather than duplicated.

**Comment by mahaase** [comment]
but wouldn't it be a good idea to split it into 2 recipes, so the bootstrap don't have to be the newest cmake version to build cmake?

**Comment by jkloetzke** [comment]
But what's the point? The bootstrap cmake is just used to build the real cmake. It's not used for something else. With proper binary artifacts nobody should ever need to build it anyway. And I don't expect the user to switch the cmake version too often.

**Comment by mahaase** [comment]
okay. understand, thx.
