### ISSUE TITLE
whitelist env vars

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#22]
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/default.yaml#L1

what's about the whitelist env vars. could we add this to the basement or should we manage this in the main project?

we figured out, the following ones by hard research:

```
whitelist:$
    - "JENKINS_HOME"    # jenkins$
    - "WORKSPACE"       # jenkins$
    - "SYSTEMDRIVE"     # msvc build by generator$
    - "TEMP"            # msvc build by generator$
    - "TMP"             # msvc build by generator$
    - "SSH_AGENT_PID"   # ssh agent$
    - "SSH_AUTH_SOCK"   # ssh agent$
    - "ProgramData"     # required for MSVS2019 detection by CMake (on some/newer installations)$
```

with that we got up msys and linux. and yes, we need both, TEMP and TMP! ;)

**Comment by jkloetzke** [comment]
As long as the variables are generic they should be added to the basement project. I'm all for it. The Jenkins variables look off limits, though. They should only be needed when doing something Jenkins specific in the recipes, right?

The windows specific variables are interesting. Most of them are already added by Bob when running *naively* on windows: https://github.com/BobBuildTool/bob/blob/d062e26446a9d57610c66b4586d4a9f987aa1834/pym/bob/input.py#L2847 I guess we should add them too when running on msys. I added them because Powershell would not work without them.

About ProgramData I'm not yet sure.

**Comment by mahaase** [comment]
but this: https://github.com/BobBuildTool/bob/blob/d062e26446a9d57610c66b4586d4a9f987aa1834/pym/bob/input.py#L2847
is just working for native windows recipes, isn't it? we need that also for msys2.
what is about ssh, is that already whitelisted in bob?
so jenkins env-vars have to be set in project default.yaml.

**Comment by jkloetzke** [comment]
> but this: https://github.com/BobBuildTool/bob/blob/d062e26446a9d57610c66b4586d4a9f987aa1834/pym/bob/input.py#L2847
> is just working for native windows recipes, isn't it? we need that also for msys2.

Right. But I think we can change this to cover MSYS2 as well.

> what is about ssh, is that already whitelisted in bob?

No. But it's common enough to add that to the basement project.

> so jenkins env-vars have to be set in project default.yaml.

Yes. This is certainly project specific and should be handled there.

**Comment by jkloetzke** [comment]
All Windows specific variables are now whitelisted by default by Bob on Windows, regardless whether run natively or on MSYS. The ssh-related variables are now whitelisted by basement. As discussed, the Jenkins specific stuff should be whitelisted in your project.
